[package]
name = "file-syncer"
version = "1.0.0"
edition = "2024"
authors = ["Joao Louro <joaocarrilholouro@gmail.com>"]
description = "A fast, lightweight event-driven file synchronizer built in Rust."
license = "MIT"
readme = "README.md"
repository = "https://github.com/JoaoCLouro/file-syncer"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
ctrlc = "3.5.2"
notify = "8.2.0"
serde = { version = "1.0.229", features = ["derive"] } # Can combine serde_derive into features
sha2 = "0.11.0"
sled = "0.34.7"
thiserror = "2.0.20"
walkdir = "2.5.0"
rkyv = { version = "0.7", features = ["validation"] }
toml = "0.8"

[dev-dependencies]
tempfile = "3.27.0"
