[package]
name = "file-syncer"
version = "0.1.0"
edition = "2024"
authors = ["Joao Louro <joaocarrilholouro@gmail.com>"]
description = "A fast, lightweight event-driven file synchronizer built in Rust."
license = "MIT"
readme = "README.md"
repository = "https://github.com/JoaoCLouro/file-syncer"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
compression = "0.1.5"
ctrlc = "3.5.2"
notify = "8.2.0"
serde = "1.0.229"
tempfile = "3.27.0"
thiserror = "2.0.20"
